defmodule Graphonomous.LongmemevalFixesTest do
  @moduledoc """
  Tests for the 7 S-split LongMemEval benchmark fixes:

  Fix 1: Adaptive retrieval params for knowledge-update questions (longmemeval.ex)
  Fix 2: knowledge_update_query? detection + 2.5x sim_limit boost (retriever.ex)
  Fix 3: Fact-prefix BM25 query variants (retriever.ex expand_query)
  Fix 4: Anti-IDK prompting for multi_session_reasoning (llm_judge.ex)
  Fix 5: Session-coverage expansion for multi-session queries (retriever.ex)
  Fix 6: Temporal chain-of-thought prompting (llm_judge.ex)
  Fix 7: Structured TIMELINE extraction for temporal_reasoning (longmemeval.ex)
  """
  use ExUnit.Case, async: true

  alias Mix.Tasks.Benchmark.Longmemeval
  alias Mix.Tasks.Benchmark.LlmJudge

  # ── Fix 1: Adaptive retrieval params ──────────────────────────────

  describe "Fix 1: adaptive retrieval params for knowledge-update" do
    test "knowledge-update type gets wider retrieval limits (30, 60, 2)" do
      # The adaptive params are in a case statement inside run_single_question.
      # We test the pattern match indirectly by verifying the format_longmemeval_context
      # function handles knowledge_update ability correctly with expected input shape.
      chunks = [
        %{
          document_date: "2023-01-15",
          turn: "3",
          text: "I own 2 bikes.",
          speaker: "user",
          session_id: "s1",
          is_superseded: true,
          valid_until: nil,
          similarity: 0.8,
          node_id: "n1",
          event_date: nil
        },
        %{
          document_date: "2023-04-01",
          turn: "5",
          text: "I now own 4 bikes.",
          speaker: "user",
          session_id: "s2",
          is_superseded: false,
          valid_until: nil,
          similarity: 0.9,
          node_id: "n2",
          event_date: nil
        }
      ]

      result = Longmemeval.format_longmemeval_context(chunks, :knowledge_update)
      assert is_binary(result)
      assert String.contains?(result, "SUPPORTING EVIDENCE")
    end
  end

  # ── Fix 2: knowledge_update_query? detection ──────────────────────

  describe "Fix 2: knowledge_update_query? detection via retrieval" do
    # knowledge_update_query? is private, so we test it indirectly by ensuring
    # retrieval completes without error on knowledge-update-style queries.
    # The actual boost (2.5x sim_limit) can't be directly observed from outside.

    @tag :integration
    test "knowledge-update queries complete retrieval without error" do
      queries = [
        "What is my current address?",
        "How many bikes do I own?",
        "Where did John move to?",
        "Do I still have a dog?",
        "What are my hobbies?",
        "Which car do I drive?"
      ]

      for q <- queries do
        result =
          Graphonomous.retrieve_context(q,
            similarity_limit: 5,
            final_limit: 10,
            skip_topology: true
          )

        assert is_list(result.results),
               "Retrieval failed for knowledge-update query: #{q}"
      end
    end
  end

  # ── Fix 3: Fact-prefix BM25 query variants ────────────────────────

  describe "Fix 3: fact-prefix BM25 variants via expand_query" do
    # expand_query is private, but we can verify the fact-prefix variant
    # is generated by checking BM25 retrieval hits when nodes have bm25_facts.

    @tag :integration
    test "retrieval finds nodes with bm25_facts metadata when query matches fact category" do
      node =
        Graphonomous.store_node(%{
          content: "[user] I own 3 cats and they are indoor cats.",
          node_type: :episodic,
          confidence: 0.7,
          source: "longmemeval-fix-test",
          metadata: %{
            "role" => "user",
            "session_id" => "fix3-test-s1",
            "bm25_facts" => ["possession: 3 cats", "possession: indoor cats"]
          }
        })

      assert is_binary(node.id)

      # Give BM25 a moment to index
      Process.sleep(100)

      # Query should trigger fact-prefix variant "possession: cats ..."
      result =
        Graphonomous.retrieve_context("How many cats do I have?",
          similarity_limit: 10,
          final_limit: 20,
          skip_topology: true
        )

      assert is_list(result.results)

      # Cleanup
      Graphonomous.Store.delete_node(node.id)
    end
  end

  # ── Fix 4: Anti-IDK prompting ─────────────────────────────────────

  describe "Fix 4: anti-IDK instruction for multi_session_reasoning" do
    test "multi_session_reasoning instruction includes anti-IDK guidance" do
      instruction = LlmJudge.ability_specific_instruction("multi_session_reasoning")
      assert String.contains?(instruction, "NEVER refuse")
      assert String.contains?(instruction, "Partial evidence")
      assert String.contains?(instruction, "ENTITY CROSS-REFERENCE")
    end

    test "other abilities do not contain anti-IDK instruction" do
      for ability <- ["abstention", "temporal_reasoning"] do
        instruction = LlmJudge.ability_specific_instruction(ability)

        refute String.contains?(instruction, "Synthesize ALL retrieved evidence"),
               "#{ability} should NOT have anti-IDK instruction"
      end
    end
  end

  # ── Fix 5: Session-coverage expansion ─────────────────────────────

  describe "Fix 5: session-coverage expansion for multi-session queries" do
    @tag :integration
    test "multi-session-style queries complete retrieval without error" do
      queries = [
        "What are both my hobbies and my job?",
        "Compare all the places I've lived",
        "How many different pets have I mentioned across conversations?",
        "Tell me about each hobby I've discussed"
      ]

      for q <- queries do
        result =
          Graphonomous.retrieve_context(q,
            similarity_limit: 10,
            final_limit: 20,
            skip_topology: true
          )

        assert is_list(result.results),
               "Retrieval failed for multi-session query: #{q}"
      end
    end
  end

  # ── Fix 6: Temporal chain-of-thought prompting ────────────────────

  describe "Fix 6: temporal reasoning chain-of-thought prompt" do
    test "temporal_reasoning instruction includes CoT steps" do
      instruction = LlmJudge.ability_specific_instruction("temporal_reasoning")
      assert String.contains?(instruction, "chronological order")
      assert String.contains?(instruction, "arithmetic")
      assert String.contains?(instruction, "Step 1")
      assert String.contains?(instruction, "ALWAYS answer")
    end
  end

  # ── Fix 7: Structured TIMELINE extraction ─────────────────────────

  describe "Fix 7: structured TIMELINE for temporal_reasoning" do
    test "temporal_reasoning format includes TIMELINE header when dates present" do
      chunks = [
        %{
          document_date: "2023-01-15",
          event_date: nil,
          turn: "1",
          text: "I started learning piano today.",
          speaker: "user",
          session_id: "s1",
          is_superseded: false,
          valid_until: nil,
          similarity: 0.9,
          node_id: "n1"
        },
        %{
          document_date: "2023-03-20",
          event_date: nil,
          turn: "2",
          text: "I performed at a recital.",
          speaker: "user",
          session_id: "s2",
          is_superseded: false,
          valid_until: nil,
          similarity: 0.85,
          node_id: "n2"
        }
      ]

      result = Longmemeval.format_longmemeval_context(chunks, :temporal_reasoning)

      assert String.contains?(result, "TIMELINE:")
      assert String.contains?(result, "2023-01-15:")
      assert String.contains?(result, "2023-03-20:")
      assert String.contains?(result, "EVIDENCE (strict chronological order)")
    end

    test "temporal_reasoning format omits TIMELINE when no dates" do
      chunks = [
        %{
          document_date: nil,
          event_date: nil,
          turn: "1",
          text: "Something happened.",
          speaker: "user",
          session_id: "s1",
          is_superseded: false,
          valid_until: nil,
          similarity: 0.9,
          node_id: "n1"
        }
      ]

      result = Longmemeval.format_longmemeval_context(chunks, :temporal_reasoning)

      refute String.contains?(result, "TIMELINE:")
      assert String.contains?(result, "EVIDENCE (strict chronological order)")
    end

    test "event_date takes precedence over document_date in timeline" do
      chunks = [
        %{
          document_date: "2023-01-15",
          event_date: "2022-12-25",
          turn: "1",
          text: "Christmas was wonderful last month.",
          speaker: "user",
          session_id: "s1",
          is_superseded: false,
          valid_until: nil,
          similarity: 0.9,
          node_id: "n1"
        }
      ]

      result = Longmemeval.format_longmemeval_context(chunks, :temporal_reasoning)

      assert String.contains?(result, "TIMELINE:")
      # event_date should appear, not document_date
      assert String.contains?(result, "2022-12-25:")
    end
  end

  # ── Knowledge-update format tests ─────────────────────────────────

  describe "knowledge_update format with superseded annotations" do
    test "superseded chunks get OUTDATED annotation" do
      chunks = [
        %{
          document_date: "2023-01-15",
          turn: "3",
          text: "I own 2 bikes.",
          speaker: "user",
          session_id: "s1",
          is_superseded: true,
          valid_until: nil,
          similarity: 0.8,
          node_id: "n1",
          event_date: nil
        },
        %{
          document_date: "2023-04-01",
          turn: "5",
          text: "I now own 4 bikes.",
          speaker: "user",
          session_id: "s2",
          is_superseded: false,
          valid_until: nil,
          similarity: 0.9,
          node_id: "n2",
          event_date: nil
        }
      ]

      result = Longmemeval.format_longmemeval_context(chunks, :knowledge_update)

      # Superseded chunk should be annotated
      assert String.contains?(result, "OUTDATED")
      assert String.contains?(result, "superseded by later information")

      # Non-superseded chunk should NOT be annotated as outdated
      lines = String.split(result, "\n")

      latest_line = Enum.find(lines, &String.contains?(&1, "I now own 4 bikes"))
      assert latest_line != nil
      refute String.contains?(latest_line, "OUTDATED")
    end

    test "valid_until chunks get OUTDATED annotation with date" do
      chunks = [
        %{
          document_date: "2023-01-15",
          turn: "3",
          text: "I live in Portland.",
          speaker: "user",
          session_id: "s1",
          is_superseded: false,
          valid_until: "2023-06-01",
          similarity: 0.8,
          node_id: "n1",
          event_date: nil
        }
      ]

      result = Longmemeval.format_longmemeval_context(chunks, :knowledge_update)
      assert String.contains?(result, "valid until 2023-06-01")
    end

    test "empty chunks return no context message" do
      result = Longmemeval.format_longmemeval_context([], :knowledge_update)
      assert result == "No relevant context found."
    end
  end

  # ── Multi-session format tests ────────────────────────────────────

  describe "multi_session_reasoning format with cross-references" do
    test "produces valid formatted output" do
      chunks = [
        %{
          document_date: "2023-01-15",
          turn: "1",
          text: "I have a dog named Rex and a cat named Whiskers.",
          speaker: "user",
          session_id: "s1",
          is_superseded: false,
          valid_until: nil,
          similarity: 0.9,
          node_id: "n1",
          event_date: nil
        },
        %{
          document_date: "2023-03-01",
          turn: "2",
          text: "Rex is doing well and I got a new fish.",
          speaker: "user",
          session_id: "s2",
          is_superseded: false,
          valid_until: nil,
          similarity: 0.85,
          node_id: "n2",
          event_date: nil
        }
      ]

      result = Longmemeval.format_longmemeval_context(chunks, :multi_session_reasoning)

      assert is_binary(result)
      assert String.contains?(result, "I have a dog named Rex")
      assert String.contains?(result, "Rex is doing well")
    end
  end

  # ── detect_fact_version tests ─────────────────────────────────────

  describe "detect_fact_version" do
    setup do
      on_exit(fn ->
        try do
          case Graphonomous.query_graph(%{operation: "list_recent", limit: 50}) do
            %{results: nodes} when is_list(nodes) ->
              Enum.each(nodes, fn n ->
                id = Map.get(n, :id) || Map.get(n, "id")
                if is_binary(id), do: Graphonomous.Store.delete_node(id)
              end)

            _ ->
              :ok
          end
        rescue
          _ -> :ok
        end
      end)

      :ok
    end

    @tag :integration
    test "overlapping fact categories detected as :updates" do
      n1 =
        Graphonomous.store_node(%{
          content: "[user] I prefer sushi for dinner.",
          node_type: :episodic,
          confidence: 0.7,
          source: "fact-version-test",
          metadata: %{
            "role" => "user",
            "session_id" => "fv-s1",
            "bm25_facts" => ["preference: sushi"]
          }
        })

      n2 =
        Graphonomous.store_node(%{
          content: "[user] I've switched to Italian food, pasta is my favorite.",
          node_type: :episodic,
          confidence: 0.7,
          source: "fact-version-test",
          metadata: %{
            "role" => "user",
            "session_id" => "fv-s2",
            "bm25_facts" => ["preference: Italian food", "preference: pasta"]
          }
        })

      result = Longmemeval.detect_fact_version(n1.id, n2.id)
      assert result == :updates

      # Cleanup
      Graphonomous.Store.delete_node(n1.id)
      Graphonomous.Store.delete_node(n2.id)
    end

    @tag :integration
    test "non-overlapping categories detected as :related" do
      n1 =
        Graphonomous.store_node(%{
          content: "[user] I like hiking.",
          node_type: :episodic,
          confidence: 0.7,
          source: "fact-version-test",
          metadata: %{
            "role" => "user",
            "session_id" => "fv-s3",
            "bm25_facts" => ["hobby: hiking"]
          }
        })

      n2 =
        Graphonomous.store_node(%{
          content: "[user] I live in Seattle.",
          node_type: :episodic,
          confidence: 0.7,
          source: "fact-version-test",
          metadata: %{
            "role" => "user",
            "session_id" => "fv-s4",
            "bm25_facts" => ["location: Seattle"]
          }
        })

      result = Longmemeval.detect_fact_version(n1.id, n2.id)
      assert result == :related

      # Cleanup
      Graphonomous.Store.delete_node(n1.id)
      Graphonomous.Store.delete_node(n2.id)
    end
  end
end
