import * as W from "/home/travis/ProjectAmp2/WRL/wrl.js";
const s = W.serializeArtifact;
const t = (label, fn) => { try { console.log(`${label.padEnd(30)} => ${fn()}`); } catch (e) { console.log(`${label.padEnd(30)} => THROWS ${e.code}: ${(e.detail||e.message).slice(0,120)}`); } };
t("nested sorted",      () => s({ b: 1, a: [3, { z: true, y: null }], c: "x" }));
t("bigint 2^63-1",      () => s({ n: 9223372036854775807n }));
t("bigint 2^64-1",      () => s({ n: 18446744073709551615n }));
t("negative bigint",    () => s({ n: -5n }));
t("safe int max",       () => s({ n: 9007199254740991 }));
t("unsafe number 2^53", () => s({ n: 9007199254740992 }));
t("float 1.5",          () => s({ f: 1.5 }));
t("NaN",                () => s({ x: NaN }));
t("Infinity",           () => s({ x: Infinity }));
t("-0",                 () => s({ x: -0 }));
t("undefined value",    () => s({ x: undefined }));
t("undefined in array", () => s([1, undefined, 2]));
t("null top",           () => s(null));
t("Date object",        () => s({ d: new Date(0) }));
t("Map object",         () => s({ m: new Map([["a", 1]]) }));
t("function value",     () => s({ f: () => 1 }));
t("unicode string",     () => s({ s: "é", u: "\u2603", ctl: "\u0001\n" }));
t("unicode keys sort",  () => s({ "é": 1, "z": 2, "Z": 3, "ü": 4, "_": 5, "1": 6, "a": 7 }));
t("empty containers",   () => s({ a: {}, b: [] }));
t("string escapes",     () => s({ q: 'he said "hi"\\', slash: "a/b", del: "\u007f" }));
t("symbol key ignored", () => s({ [Symbol("x")]: 1, a: 1 }));
t("proto key",          () => s({ ["__proto__"]: 1, a: 2 }));
