#!/usr/bin/env python3
"""Regenerate projections/EVIDENCE.md from the built projections (every number is read from files or from `g0 verify`,
`g0 census` and the Python twin). Usage: python3 tools/evidence.py [baseline historical …]. The pre-B.1 receipts under
projections/pre-b1/ and the pre-D-034 receipts under projections/pre-d034/ are reported from their own files and never
rebuilt."""
import json, subprocess, collections, os, sys
names = sys.argv[1:] or ["baseline", "historical"]
labels = {"baseline": "baseline / current-at-freeze (invariant-r10@ba4e625, package-v2.7)", "historical": "historical (invariant-r10@699fbc2, package-v2.6)"}
out = ["# Projection evidence — G0-B.1 + D-037 + G0-C sealed by WRL-P0 (generated by tools/evidence.py; every number is read from the files or the named commands)\n"]
out.append("## Pre-B.1 receipts (superseded, preserved — D-033)\n")
for name in names:
    d = f"projections/pre-b1/{name}"
    if not os.path.isdir(d): continue
    root = open(f"{d}/ROOT").read().strip(); man = json.load(open(f"{d}/manifest.json"))
    ver = json.loads(subprocess.run(["node", "bin/g0.mjs", "verify", "--dir", d], capture_output=True, text=True).stdout)
    out.append(f"- `{name}` pre-B.1 root `{root}` — {man['count']} entries, ruleset `{man['ruleset']}`; `g0 verify` today: checked {ver['checked']}/{ver['entries']}, problems {ver['problems']}; superseded by the B.1 root below")
out.append("")
out.append("## Pre-D-034 receipts (superseded, preserved — D-037)\n")
for name in names:
    d = f"projections/pre-d034/{name}"
    if not os.path.isdir(d): continue
    root = open(f"{d}/ROOT").read().strip(); man = json.load(open(f"{d}/manifest.json"))
    ver = json.loads(subprocess.run(["node", "bin/g0.mjs", "verify", "--dir", d], capture_output=True, text=True).stdout)
    R0 = [json.loads(l) for l in open(f"{d}/records/relation.jsonl") if l.strip()]
    sup = [r for r in R0 if r["kind"] == "SUPERSEDES"]
    ev_root = open(f"{d}/derived/ROOT").read().strip() if os.path.isfile(f"{d}/derived/ROOT") else None
    gsem = open(f"{d}/world/GSEM").read().strip() if os.path.isfile(f"{d}/world/GSEM") else None
    out.append(f"- `{name}` pre-D-034 projection root `{root}` — {man['count']} entries, ruleset `{man['ruleset']}`; `g0 verify` today: checked {ver['checked']}/{ver['entries']}, problems {ver['problems']}; it carried {len(sup)} transition→claim `SUPERSEDES` ({sorted(set((r['source'].split(':')[0], r['target'].split(':')[0]) for r in sup))}); evaluation root `{ev_root}`; spike `{gsem}`; superseded by the D-037 roots below (transition→claim is `STATE_TRANSITION_OF`; the `rel-` labels of that spike are now `grelpre-`)")
out.append("")
for name in names:
    d = f"projections/{name}"; root = open(f"{d}/ROOT").read().strip(); man = json.load(open(f"{d}/manifest.json"))
    ver = json.loads(subprocess.run(["node", "bin/g0.mjs", "verify", "--dir", d], capture_output=True, text=True).stdout)
    twin = json.loads(subprocess.run(["python3", "test/canon_twin.py", "--manifest", d], capture_output=True, text=True).stdout)
    cen = json.loads(subprocess.run(["node", "bin/g0.mjs", "census", "--dir", d], capture_output=True, text=True).stdout)
    F = [json.loads(l) for l in open(f"{d}/records/fault.jsonl") if l.strip()]; snap = json.load(open(f"{d}/snapshot.json"))
    N = {json.loads(l)["lid"]: json.loads(l) for l in open(f"{d}/records/node.jsonl") if l.strip()}
    R = [json.loads(l) for l in open(f"{d}/records/relation.jsonl") if l.strip()]
    A = {json.loads(l)["lid"]: json.loads(l) for l in open(f"{d}/records/assertion.jsonl") if l.strip()}
    out.append(f"## {labels.get(name, name)}\n")
    out.append(f"- projection root (TRVM CAS `root-`): `{root}`")
    out.append(f"- manifest: {man['count']} entries; ruleset `{man['ruleset']}`; spec `{man['spec']}`; snapshot `{man['snapshot']}`")
    out.append(f"- `g0 verify`: checked {ver['checked']}/{ver['entries']}, problems {ver['problems']}; CAS objects on disk: {len(os.listdir(d + '/cas'))}")
    out.append(f"- Python twin (`canon_twin.py --manifest`): checked {twin['checked']}, root_twin == ROOT: {twin['root_twin'] == root}, problems {twin['problems']}")
    out.append(f"- records by kind: {json.dumps(cen['by_prefix'])}")
    out.append(f"- node kinds: {json.dumps(cen['node_kinds'])}")
    out.append(f"- relation kinds: {json.dumps(cen['relation_kinds'])}")
    sto = [r for r in R if r["kind"] == "STATE_TRANSITION_OF"]; sup = [r for r in R if r["kind"] == "SUPERSEDES"]
    out.append(f"- D-037: STATE_TRANSITION_OF {len(sto)} (endpoint pairs {sorted(set((r['source'].split(':')[0], r['target'].split(':')[0]) for r in sto))}; attrs keys {sorted(set().union(*(set(r['attrs']) for r in sto)) if sto else [])}); SUPERSEDES {len(sup)} (endpoint pairs {sorted(set((r['source'].split(':')[0], r['target'].split(':')[0]) for r in sup))}) — no SUPERSEDES is inferred from the transition chain")
    hist = collections.Counter(len(r["assertions"]) for r in R)
    out.append(f"- B.1 fold: {len(R)} relations (propositions) carry {sum(len(r['assertions']) for r in R)} assertions; relations by assertion count {json.dumps(dict(sorted(hist.items())))}; relation-level attribute keys by kind {json.dumps({k: sorted(v) for k, v in sorted(((k, set().union(*(set(r['attrs']) for r in R if r['kind'] == k))) for k in set(r['kind'] for r in R))) if v})}")
    out.append(f"- faults: {len(F)} — by code {json.dumps(dict(sorted(collections.Counter(f['code'] for f in F).items())))}; by rule {json.dumps(dict(sorted(collections.Counter(f['rule'] for f in F).items())))}")
    out.append("- pinned sources: " + "; ".join(f"`{s['repo']}@{s['commit'][:12]}` ({len(s['files'])} files, tree `{s['tree'][:12]}`)" for s in snap["sources"]))
    tested = [l for l, n in N.items() if n["kind"] == "CLAIM" and n["attrs"].get("token_family") == "TESTED"]
    def executed_occurrence(r): return any((A[a].get("attrs") or {}).get("executed") is True for a in r["assertions"])
    observed = set(r["target"] for r in R if r["kind"] == "WITNESSES" and r["source"].startswith("receipt:") and N[r["source"]]["attrs"].get("sha256_verified_at_pin") is True and executed_occurrence(r))
    part = {"EXEC_RECEIPT_OBSERVED": sorted(l.split(":")[-1] for l in tested if l in observed), "NO_EXEC_RECEIPT_OBSERVED": sorted(l.split(":")[-1] for l in tested if l not in observed and N[l]["attrs"].get("receipts_typed") is True), "EXEC_RECEIPT_UNDECIDABLE_FROM_SOURCE": sorted(l.split(":")[-1] for l in tested if l not in observed and N[l]["attrs"].get("receipts_typed") is not True)}
    out.append(f"- A6 partition over the {len(tested)} TESTED-family claims (D-022 names; D-032 admissibility rule from records): " + "; ".join(f"{k} {len(v)} {v if len(v) <= 6 else v[:6] + ['…']}" for k, v in part.items()))
    opens = [r for r in R if r["kind"] == "OPENS" and r["source"] == "round:computedriven:R0.8"]
    desc = []
    for r in sorted(opens, key=lambda r: r["target"]):
        n = N[r["target"]]; cites = sorted(set(x["target"].split(":")[-1] for x in R if x["kind"] == "CITES" and x["source"] == r["target"]))
        desc.append((n["attrs"].get("code") or ("unnamed: " + n["attrs"].get("text", "")[:60] + "…")) + (f" (cites {cites})" if cites else "") + f" [{len(r['assertions'])} assertion(s) from {sorted(set(A[a]['asserted_by'].split(':')[1] for a in r['assertions']))}]")
    out.append(f"- A2 at this snapshot: `round:computedriven:R0.8` OPENS {desc}")
    bare = [r for r in R if r["kind"] == "CITES" and any((A[a].get("attrs") or {}).get("qualified") is False for a in r["assertions"])]
    out.append(f"- D-031 bare identifiers resolved (each with an UNQUALIFIED_REFERENCE fault): {sorted(r['target'] for r in bare)}")
    ev = f"{d}/derived"
    if os.path.isdir(ev):
        em = json.load(open(f"{ev}/manifest.json"))
        out.append(f"- G0-E evaluation (`derived/`): {em['count']} derived facts by rule {json.dumps(em['by_rule'])}; derivation-set digest `{em['digest']}`; evaluation root `{open(f'{ev}/ROOT').read().strip()}`; bound to projection root {em['projection_root'] == root}; ruleset `{em['ruleset']}`; `trvm_derivation`: {em['trvm_derivation']}; independent checker: {em.get('checker', {})}")
        DF = [json.loads(l) for l in open(f"{ev}/facts.jsonl") if l.strip()]
        PREFIX_KIND = {"claim": "CLAIM", "transition": "EVIDENCE_STATE_TRANSITION", "obligation": "OBLIGATION", "round": "ROUND"}
        her = collections.Counter(PREFIX_KIND.get(f["args"][0].split(":")[0], f["args"][0].split(":")[0]) for f in DF if f["rel"] == "has_exec_receipt")
        cur = set(f["args"][0] for f in DF if f["rel"] == "current"); sup_d = sorted(f["args"][0].split(":")[-1] for f in DF if f["rel"] == "superseded")
        out.append(f"- D-037 derived: `superseded` {sup_d}; `current` holds every claim with a recorded transition: {sorted(l.split(':')[-1] for l in N if N[l]['kind'] == 'CLAIM' and l in cur and any(r['kind'] == 'STATE_TRANSITION_OF' and r['target'] == l for r in R))}; `has_exec_receipt` is generic over its subject — subjects by node kind {json.dumps(dict(sorted(her.items())))}")
    wd = f"{d}/world"; ws = f"{d}/world-spike"
    if os.path.isdir(wd) and os.path.isfile(f"{wd}/SEM"):
        wi = json.load(open(f"{wd}/identities.json")); sem = open(f"{wd}/SEM").read().strip()
        revs = collections.Counter(r["rev"] for r in wi["relations"])
        import re
        rel_ok = sum(1 for r in wi["relations"] if re.fullmatch(r"rel-[0-9a-f]{64}", r["rel"])); rev_ok = sum(1 for r in wi["relations"] if re.fullmatch(r"rev-[0-9a-f]{64}", r["rev"]))
        art = open(f"{wd}/artifact.json", encoding="utf8").read()
        out.append(f"- G0-C SEALED world (`world/`, WRL-P0): `{sem}` (identities.json agrees: {wi['sem'] == sem}) over {wi['objects']} objects and {len(wi['relations'])} relations under `{wi['profile_id']}`; WRL `{wi['wrl']['commit'][:7]}` (blobs {', '.join(b['file'] + '@' + b['blob'][:8] for b in wi['wrl']['blobs'])}); bound to projection root {wi['projection_root'] == root} (the world is outside the projection root); canonical bytes {os.path.getsize(f'{wd}/artifact.json')}; kernel-minted `rel-` {rel_ok}/{len(wi['relations'])}, `rev-` {rev_ok}/{len(wi['relations'])} ({len(revs)} distinct, {sum(1 for c in revs.values() if c > 1)} shared by more than one relation), every relation labelled `{sorted(set(r['minted_by'] for r in wi['relations']))}`; no id string of any family inside the sealed bytes: {not re.search(r'(sem|rel|rev|gsem|grelpre)-[0-9a-f]{64}', art)}; state `{wi['state']}`")
        sp = wi.get("supersedes", {}); gsem = open(f"{ws}/GSEM").read().strip() if os.path.isfile(f"{ws}/GSEM") else None
        out.append(f"- supersession (D-038/D-041): historical spike `{sp.get('historical_spike_gsem')}` (world-spike/GSEM agrees: {gsem == sp.get('historical_spike_gsem')}); measured: spike hex == sem hex {gsem is not None and gsem[5:] == sem[4:]} (the spike reproduced WRL's canonicalization byte for byte at this pin — a measurement, not a rule; the spike is not a seal); `gsem-`/`grelpre-` strings in world/identities.json outside `supersedes`: {len(re.findall(r'gsem-|grelpre-', open(f'{wd}/identities.json').read())) - 1}")
    elif os.path.isdir(wd):
        wi = json.load(open(f"{wd}/identities.json"))
        out.append(f"- G0-C spike (`world/`, PROVISIONAL — D-036): `{wi['gsem']}` over {wi['objects']} objects and {len(wi['relations'])} relations (not yet sealed by WRL)")
    out.append("")
out.append("## Determinism (test/projection.test.mjs, A8 / B1-8)\n\nThe baseline is built four times inside the test — plain; a seeded shuffle of every input list plus reversed adapter order; a second seed; reversed adapter order alone — and every hashed file is compared byte for byte; the roots are equal. `witness.json` (timestamps, host, seeds) lives outside the digest and differs by design.\n")
out.append("## What these projections do not claim\n\nEvery node and relation record is `basis: observed`. Derived facts, when present, live in `derived/` with `basis: derived`, `trvm_derivation: false` and a derivation per fact replayed by the independent checker; they never enter the observed projection root. The `sem-` under `world/` is WRL's seal of the SEMANTIC STATEMENT world of the projection (D-041 §8), computed by WRL from the submitted artifact and stored outside the projection root; it is not a registry write and not a TRVM derivation (the ruleset id in the manifest binds the rule program, not an evaluation). Fault rows are source facts, not verdicts.\n")
open("projections/EVIDENCE.md", "w").write("\n".join(out) + "\n"); print("\n".join(out))
