#!/usr/bin/env node
/* g0d_vectors.mjs — write handoff/G0D_GOLDEN_VECTORS.md: per pin, every certificate identity read back from the shipped
 * `certificate/bundle.json` + `VCLAIM` and re-derived by the checker; the certificate preimage length; and the sensitivity
 * table (what MOVED / HELD under each mutation, with the refusal code the checker gives the mutated bundle over the shipped
 * directory). Reads only — the shipped projections are never modified; mutations are in memory.
 *   node tools/g0d_vectors.mjs */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { checkCertificate, snapshotCommitment, claimSemId, aggregateId, structureSemId, certificatePreimage, liveChainIds, PROTOCOL, CLAIM_FIELD, CHECKER_ID, PROJECTOR_MODULES, CHECKER_IMPORTS } from "../lib/certificate.mjs";
import { verifiedClaimSemId, certificateOf } from "../../../TRVM/governance/certificate.mjs";
import { TRVM_PIN } from "../lib/canon.mjs";
import { canonicalWireBytes } from "../../../TRVM/governance/cas.mjs";

const V = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PINS = ["baseline", "historical", "multi"];
const clone = (o) => JSON.parse(JSON.stringify(o));
const reseal = (b) => { b.claim[CLAIM_FIELD] = claimSemId(b.claim); b.aggregate.aggregate_id = aggregateId(b.aggregate); b.structure.structure_sem_id = structureSemId(b.structure); return b; };
const vclaimOf = (b) => { try { return verifiedClaimSemId(certificateOf(b, CLAIM_FIELD)); } catch (e) { return "(" + e.message + ")"; } };
const LABEL = `at TRVM ${TRVM_PIN.commit.slice(0, 7)} (TRVM-P0 landed: the pin moved from fd0df4c and every certificate was re-minted; the fd0df4c-era and G0-F-intermediate ids are recorded in D-058)`;

const out = [`# G0-D golden vectors — \`${PROTOCOL}\` ${LABEL}`, ``,
  `Generated by \`node tools/g0d_vectors.mjs\` from the shipped \`projections/<pin>/certificate/{bundle.json,VCLAIM}\`; every id is read from the bundle AND re-derived by \`checkCertificate\` over the directory (the two must agree, and the verdict says so). The certificate identity is TRVM's \`verifiedClaimSemId\` (\`TRVM-VERIFIED-CLAIM-v1\`) over (protocol, projection_claim_sem_id, aggregate_id, chain_ids). Not a warrant: possession of a \`vclaim-\` establishes nothing (D-054). Chain: TRVM pin \`${TRVM_PIN.commit}\` with ${Object.keys(TRVM_PIN.blobs).length} pinned blobs; projector modules ${PROJECTOR_MODULES.join(", ")}; checker \`${CHECKER_ID}\` importing ${CHECKER_IMPORTS.join(", ")}.`, ``];
const sensitivity = [];
for (const pin of PINS) {
  const dir = resolve(V, "projections", pin); const bundle = JSON.parse(readFileSync(join(dir, "certificate/bundle.json"), "utf8")); const vclaim = readFileSync(join(dir, "certificate/VCLAIM"), "utf8").trim();
  const r = checkCertificate(dir); const m = r.measured; const pre = certificatePreimage(certificateOf(bundle, CLAIM_FIELD));
  out.push(`## ${pin}`, ``, `| identity | value (bundle) | re-derived by the checker equals |`, `|---|---|---|`);
  // compared as CANONICAL text, never JSON.stringify: a bundle read back is key-sorted, a live record is insertion-ordered (the live_dag.mjs key-order trap)
  const row = (k, b, d) => out.push(`| ${k} | \`${typeof b === "string" ? b : canonicalWireBytes(b)}\` | ${canonicalWireBytes(b).equals(canonicalWireBytes(d ?? null)) ? "yes" : "NO — " + canonicalWireBytes(d ?? null)} |`);
  row("projection_root", bundle.claim.projection_root, m.projection_root); row("snapshot_id", bundle.claim.snapshot_id, m.snapshot_id); row("snapshot_commitment", bundle.claim.snapshot_commitment, m.snapshot_commitment);
  row("spec", bundle.claim.spec, m.spec); row("ruleset", bundle.claim.ruleset, m.ruleset); row("schema_set_id", bundle.claim.schema_set_id, m.schema_set_id); row("adapter_contract_id", bundle.claim.adapter_contract_id, m.adapter_contract_id);
  row("projection_claim_sem_id", bundle.claim[CLAIM_FIELD], m.projection_claim_sem_id); row("aggregate_id", bundle.aggregate.aggregate_id, m.aggregate_id);
  row("chain_ids.trvm_commit", bundle.chain_ids.trvm_commit, m.chain_ids?.trvm_commit); row("chain_ids.trvm_blobs", bundle.chain_ids.trvm_blobs.map((b) => `${b.file}@${b.blob.slice(0, 8)}`).join(" "), m.chain_ids?.trvm_blobs.map((b) => `${b.file}@${b.blob.slice(0, 8)}`).join(" "));
  row("chain_ids.projector", bundle.chain_ids.projector, m.chain_ids?.projector); row("chain_ids.checker", bundle.chain_ids.checker, m.chain_ids?.checker);
  row("references.operands[snapshot].artifact_root", bundle.references.operands[1].artifact_root, m.snapshot_root); row("structure", bundle.structure, m.structure);
  row("verified_claim_sem_id (VCLAIM)", vclaim, m.verified_claim_sem_id);
  out.push(`| bundle artifact root | \`${r.measured.bundle_bytes} canonical bytes\` | — |`, ``,
    `- \`checkCertificate\` verdict: **${r.verdict}** (codes ${JSON.stringify(r.codes)}); entries checked ${m.entries_checked}/${m.entries}; CAS objects ${m.cas_objects} (= entries + manifest + snapshot record); sources ${m.sources}, pinned files ${m.files_pinned}; writes ${m.writes}`,
    `- certificate preimage (\`TRVM-VERIFIED-CLAIM-v1|\` + canonical bytes of {aggregate_id, certificate_protocol, chain_ids, claim_sem_id, protocol}): **${pre.length} octets**; sha256 → \`${vclaim}\` (re-derived by hand in test/certificate.test.mjs (1))`, ``);
  if (pin === "baseline") {
    const cases = [
      ["projection_root changed", (b) => { b.claim.projection_root = "root-" + "0".repeat(64); }],
      ["snapshot: source dropped (commitment recomputed)", (b) => { const s = JSON.parse(readFileSync(join(dir, "snapshot.json"), "utf8")); s.sources = s.sources.filter((x) => x.namespace !== "trvm"); b.claim.snapshot_commitment = snapshotCommitment(s); }],
      ["snapshot: sources reordered (commitment recomputed)", (b) => { const s = JSON.parse(readFileSync(join(dir, "snapshot.json"), "utf8")); s.sources = s.sources.slice().reverse(); b.claim.snapshot_commitment = snapshotCommitment(s); }],
      ["snapshot relabelled (snapshot_id)", (b) => { b.claim.snapshot_id = "snapshot:g0:other"; }],
      ["spec changed", (b) => { b.claim.spec = "G0_G1_SPEC.md@2099-01-01"; }],
      ["ruleset changed", (b) => { b.claim.ruleset = "g0rule-" + "1".repeat(64); }],
      ["ruleset absent", (b) => { delete b.claim.ruleset; }],
      ["schema set changed", (b) => { b.claim.schema_set_id = "gschema-x"; }],
      ["adapter contract changed", (b) => { b.claim.adapter_contract_id = "gadapt-x"; }],
      ["scope.truth_claimed = true", (b) => { b.claim.scope.truth_claimed = true; }],
      ["protocol id bumped to v1", (b) => { b.protocol = "GRAPHONOMOUS-PROJECTION-v1"; }],
      ["TRVM pin moved (chain_ids.trvm_commit)", (b) => { b.chain_ids.trvm_commit = "deadbeef".repeat(5); }],
      ["projector code moved (chain_ids.projector.code)", (b) => { b.chain_ids.projector.code = "gcode-" + "2".repeat(64); }],
      ["aggregate: fault count changed", (b) => { b.aggregate.faults.count += 1; }],
      ["structure: cas_objects changed", (b) => { b.structure.cas_objects += 1; }],
      ["references: snapshot artifact_root changed", (b) => { b.references.operands[1].artifact_root = "root-" + "3".repeat(64); }],
      ["annotations reworded / witness.json / README (unbound)", (b) => { b.annotations.note = "reworded"; }],
    ];
    sensitivity.push(`## Sensitivity (baseline; every mutation re-sealed by the forger — claim/aggregate/structure ids recomputed beside the mutated record)`, ``, `| mutation | projection_claim_sem_id | certificate (vclaim-) | checker over the shipped directory |`, `|---|---|---|---|`);
    for (const [name, mutate] of cases) {
      const b = clone(bundle); mutate(b); try { reseal(b); } catch { /* an absent ruleset cannot be re-sealed under the G0 domain; the checker names it anyway */ }
      const claimMoved = b.claim[CLAIM_FIELD] !== bundle.claim[CLAIM_FIELD]; const v = vclaimOf(b); const rr = checkCertificate(dir, b);
      sensitivity.push(`| ${name} | ${claimMoved ? "MOVED" : "HOLDS"} | ${v === vclaim ? "HOLDS" : "MOVED"} | ${rr.verdict}${rr.codes.length ? " " + rr.codes.join(", ") : ""} |`);
    }
    sensitivity.push(``, `Reading: the claim binds WHAT was reconstructed and FROM WHAT (root, snapshot label + set commitment, spec, ruleset, schema set, adapter contract, scope); the certificate additionally binds the evidence aggregate and the chain (TRVM pin, projector, checker); the reference and structure planes are authenticated by the bundle's own artifact root and are outside both — a reordered source set or a reworded annotation changes the ARTIFACT and not the CERTIFICATE. The checker judges relations to the directory it is handed, so every mutation of a bound value is refused by that value's own code whether or not the forger re-sealed the ids.`, ``);
  }
}
out.push(...sensitivity, `## Cross-pin`, ``, `- the two certificates differ only in projection_root, snapshot_id, snapshot_commitment, aggregate (and so projection_claim_sem_id, aggregate_id, verified_claim_sem_id): ruleset, spec, schema_set_id, adapter_contract_id, scope and chain_ids are identical (test/certificate.test.mjs (6)); each directory refuses the other's bundle \`gproj-root-mismatch\` + \`gproj-snapshot-commitment-mismatch\` + \`gproj-certificate-stale\`.`, `- live chain at generation: \`${JSON.stringify(liveChainIds())}\``, ``);
writeFileSync(resolve(V, "handoff/G0D_GOLDEN_VECTORS.md"), out.join("\n") + "\n");
console.log(out.join("\n"));
