#!/usr/bin/env node
/* identity_matrix.mjs — measure the G0-C identity-change matrix on the baseline projection through the REAL WRL seal
 * (D-043) and write handoff/G0C_IDENTITY_MATRIX.md. Five edits: none / shuffle / assertion-only / one relation attribute /
 * one node attribute. Every sem-/rel-/rev- is WRL's (lib/wrl_world.mjs → relation-v2.js); nothing here hashes.
 *   node tools/identity_matrix.mjs [projections/baseline] */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { assertWrlPinned, WRL_PIN, semanticArtifact, seal } from "../lib/wrl_world.mjs";
import { loadProjection } from "../lib/evaluation.mjs";
import { canonicalBytesG0, hashOfBytes, artifactRoot } from "../lib/canon.mjs";

const V = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dir = resolve(V, process.argv[2] || "projections/baseline");
assertWrlPinned();
const P = loadProjection(dir);
const clone = (p) => JSON.parse(JSON.stringify({ root: p.root, snapshot: p.snapshot, nodes: p.nodes, relations: p.relations, assertions: p.assertions, locations: p.locations }));
const shuffled = (arr, seed) => { const a = arr.slice(); let s = (seed >>> 0) || 1; for (let i = a.length - 1; i > 0; i--) { s = (s * 1103515245 + 12345) >>> 0; const j = s % (i + 1); [a[i], a[j]] = [a[j], a[i]]; } return a; };

const edits = {
  "none (re-seal)": { apply: (c) => c },
  "shuffle every record list": { apply: (c) => { c.nodes = shuffled(c.nodes, 7); c.relations = shuffled(c.relations, 8); c.locations = shuffled(c.locations, 9); c.assertions = shuffled(c.assertions, 10); return c; } },
  "assertion-only (provenance) edit": { apply: (c) => { const a = c.assertions.find((x) => x.attrs && x.attrs.role); a.attrs.role += "-edited"; a.attrs.extra_note = "provenance only"; c.edited_lid = a.lid; c.edited_record = a; return c; } },
  "one relation attribute edit (a STATES relation_field)": { apply: (c) => { const r = c.relations.find((x) => x.kind === "STATES"); r.attrs = { ...r.attrs, relation_field: r.attrs.relation_field + "*" }; c.edited_lid = r.lid; return c; } },
  "one node attribute edit (a CLAIM name)": { apply: (c) => { const n = c.nodes.find((x) => x.kind === "CLAIM"); n.attrs = { ...n.attrs, name: n.attrs.name + " (edited)" }; c.edited_lid = n.lid; return c; } },
};

const S0 = await seal(semanticArtifact(P));
const rev0 = new Map(S0.relations.map((r) => [r.relation_name, r.rev])), rel0 = new Map(S0.relations.map((r) => [r.relation_name, r.rel]));
const rows = [];
for (const [name, e] of Object.entries(edits)) {
  const c = e.apply(clone(P)); const S = await seal(semanticArtifact(c));
  const rev = new Map(S.relations.map((r) => [r.relation_name, r.rev])), rel = new Map(S.relations.map((r) => [r.relation_name, r.rel]));
  const revMoved = [...rev0].filter(([k, v]) => rev.get(k) !== v).length, relMoved = [...rel0].filter(([k, v]) => rel.get(k) !== v).length;
  const lidsStable = JSON.stringify([...rev.keys()].sort()) === JSON.stringify([...rev0.keys()].sort());
  // projection-root sensitivity (the observed root, outside the world): recompute the manifest root with the edited record where an edit touches a record
  let rootMoved = "no (no record changed)";
  if (c.edited_record) { const h = hashOfBytes(canonicalBytesG0(c.edited_record)); const m2 = { ...P.manifest, entries: P.manifest.entries.map(([lid, x]) => (lid === c.edited_lid ? [lid, h] : [lid, x])) }; rootMoved = artifactRoot(m2) !== P.root ? "YES (recomputed manifest root)" : "no"; }
  else if (name.startsWith("one ")) rootMoved = "YES (a record changed; not recomputed here)";
  else if (name.startsWith("shuffle")) rootMoved = "no (A8: order-independent, test/projection.test.mjs)";
  rows.push({ name, sem: S.sem, semMoved: S.sem !== S0.sem, revMoved, relMoved, total: S0.relations.length, lidsStable, rootMoved, edited: c.edited_lid || "—" });
}

const md = [
  `# G0-C identity-change matrix (measured; D-043)`, ``,
  `Projection: \`${dir.replace(V + "/", "")}\` root \`${P.root}\` (snapshot \`${P.snapshot}\`). WRL pin \`${WRL_PIN.commit}\` (relation-v2.js blob \`${WRL_PIN.blobs["relation-v2.js"]}\`). Baseline seal: \`${S0.sem}\` over ${S0.objects} objects / ${S0.relations.length} relations. Every id below is WRL's (\`canonicalizeV2Artifact\` → \`v2WorldIdOfArtifact\` → \`deriveV2Relations\`); the tool only counts. Generated by \`node tools/identity_matrix.mjs\`.`, ``,
  `| edit | sem- moved? | rev- moved | rel- moved | statement lids stable? | projection root moved? | edited lid | sem- after |`,
  `|---|---|---|---|---|---|---|---|`,
  ...rows.map((r) => `| ${r.name} | ${r.semMoved ? "YES" : "no"} | ${r.revMoved}/${r.total} | ${r.relMoved}/${r.total} | ${r.lidsStable ? "yes" : "NO"} | ${r.rootMoved} | \`${r.edited}\` | \`${r.sem}\` |`),
  ``,
  `Reading (D-043): the statement lid is the cross-world name of a proposition; \`rev-\` is the content identity of one relation revision (moves only when that revision's bytes move); \`rel-\` is the allocation identity of the named relation inside one exact world, so it moves whenever the \`sem-\` moves (WRL D8.5). A provenance-only edit moves the projection root and nothing WRL seals (D-041 §8: G0-C is the semantic statement world, not the evidence world).`, ``,
].join("\n");
writeFileSync(resolve(V, "handoff/G0C_IDENTITY_MATRIX.md"), md);
console.log(md);
